---
version: 2

builds:
  - main: ./main.go
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - name_template: "{{.ProjectName}}-v{{.Version}}-{{.Os}}-{{.Arch}}"
    format_overrides:
      - goos: windows
        formats:
          - zip

checksum:
  split: true
